name: CI

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
  npm_config_yes: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.14
          actions-cache-folder: "emsdk-cache"
      - run: npm pack
      - run: mv tree-sitter-talon-*.tgz tree-sitter-talon.tgz
      - uses: actions/upload-artifact@v4
        with:
          name: tree-sitter-talon.tgz
          path: tree-sitter-talon.tgz
          if-no-files-found: error

  test:
    name: test / ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.type }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.14
          actions-cache-folder: "emsdk-cache"
      - run: npm install && npm test
    strategy:
      matrix:
        os:
          - name: "Linux"
            type: "ubuntu-latest"
            plat: "linux"
          - name: "macOS"
            type: "macos-latest"
            plat: "darwin"
          - name: "Windows"
            type: "windows-latest"
            plat: "win"

  release:
    name: release
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: tree-sitter-talon.tgz
          path: build
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/tree-sitter-talon.tgz
